version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "frugan-dev"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "area: dependencies"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "frugan-dev"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "area: dependencies"
      - "area: ci/cd"